export default Object.freeze({
  LOGIN: "LOGIN",
  REGISTER: "REGISTER",
  ONBOARDING: "ONBOARDING",
  WELCOME: "WELCOME",
  HOME: "HOME",
  EVNET_DETAIL: "EVENT_DETAILS",
  APP_HOME: "APP_HOME",
  APP_PROFILE: "APP_PROFILE",
  CHECKOUT: "CHECKOUT",
  PROFILE: "PROFILE",
});
